name: Deploy to EC2 via SSM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::558245564262:role/GitHubDeployRole
          aws-region: us-west-2

      - name: Create file locally
        run: |
          echo "Hello from GitHub Actions" > testfile.txt
          cat testfile.txt

      - name: Get EC2 instance ID
        id: get_instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=Test-ec2" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
          echo "Instance ID: $INSTANCE_ID"
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          
      - name: Transfer file to EC2 via SSM
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Copy test.tar to /tmp"


      - name: Transfer file to EC2 via SSM
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Copy testfile.txt to /tmp" \
            --parameters 'commands=["cat > /tmp/testfile.txt <<EOF
          '"$(cat testfile.txt)"'
          EOF"]'
